# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#########################
# Travis CI configuration
#########################
---

# Run tests against pull requests and main branches only
if: |
  type = pull_request OR \
  branch IN (master, develop)

language: generic

# Install Ansible and Python development packages
addons:
  apt:
    packages:
      - python-pip
      - python-dev
    update: true
  homebrew:
    packages:
      - ansible
      - pre-commit
    update: true

cache:
  directories:
    - $HOME/.cache/pre-commit/

install:
  # Install Ansible with pip on Ubuntu
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      if [[ -z "$ANSIBLE_VERSION" ]]; then
        pip install --user ansible
      else
        pip install --user ansible${ANSIBLE_VERSION}
      fi
    fi

  # Install pre-commit with pip on Ubuntu
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      pip install --user pre-commit
    fi

  # Check Ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\n' > ansible.cfg

before_script:
  # https://github.com/travis-ci/travis-ci/issues/6307
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm get head || true
    fi

script:

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test role run
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Test idempotence
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test command line tools have been installed are are available
  - >
    source ~/.bashrc
    && command -v aws
    && aws --version
  - >
    source ~/.bashrc
    && command -v aws-shell
  - >
    source ~/.bashrc
    && command -v aws-vault
    && aws-vault --version
  - >
    source ~/.bashrc
    && command -v cli53
    && cli53 --version
  - >
    source ~/.bashrc
    && command -v aws-tools-update

before_cache:
  - rm -f $HOME/.cache/pre-commit/pre-commit.log

stages:
  - validate
  - test

jobs:
  include:

    # Run validation stage in Linux with latest Ansible only
    - stage: validate
      name: Validate with pre-commit
      os: linux
      dist: xenial
      language: minimal
      script:
        - pre-commit run -a

  # Run tests
    - stage: test
      name: "Ubuntu 16.04 (Xenial) with Ansible 2.6"
      os: linux
      dist: xenial
      env: ANSIBLE_VERSION='<2.7.0'
    - stage: test
      name: "Ubuntu 16.04 (Xenial) with Ansible 2.7"
      os: linux
      dist: xenial
      env: ANSIBLE_VERSION='<2.8.0'
    - stage: test
      name: "Ubuntu 18.04 (Bionic) with Ansible 2.8"
      os: linux
      dist: bionic
      env: ANSIBLE_VERSION='<2.9.0'

    - stage: test
      name: "macOS 10.13 (High Sierra) with Xcode 10.1"
      os: osx
      osx_image: xcode10.1
    - stage: test
      name: "macOS 10.14 (Mojave) with Xcode 10.2.1"
      os: osx
      osx_image: xcode10.2

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
