---

- name: Linux | Create directory for cli53
  file:
    path: "{{ aws_tools_dir }}/cli53-{{ cli53_version }}"
    state: directory

- name: Linux | Download cli53 binary from GitHub
  get_url:
    url: https://github.com/barnybug/cli53/releases/download/{{ cli53_version }}/{{ cli53_binary }}
    dest: "{{ aws_tools_dir }}/cli53-{{ cli53_version }}/cli53"
    checksum: "{{ cli53_checksum }}"
    mode: 0755

- name: Linux | Symlink cli53 to /usr/local/bin
  file:
    src: "{{ aws_tools_dir }}/cli53-{{ cli53_version }}/cli53"
    dest: "{{ aws_bin_dir }}/cli53"
    state: link

- name: Linux | Get cli53 version
  command: cli53 --version
  register: cli53_installed_version
  changed_when: False
  when: cli53_check_version

- name: Linux | Check that cli53 is not out of date
  assert:
    that: "'cli53 version {{ cli53_version }}' == '{{ cli53_installed_version.stdout }}'"
  when: cli53_check_version