---

- name: Install awscli with Homebrew
  homebrew:
    name: awscli

- name: Install aws-shell with Homebrew
  homebrew:
    name: aws-shell

- name: Install cli53 with Homebrew
  homebrew:
    name: cli53

- name: Install aws-vault with Homebrew
  homebrew_cask:
    name: aws-vault
  when: aws_tools_install_aws_vault | default(true)
