---

- name: OS X | Install AWS CLI tools with Homebrew
  homebrew:
    name: awscli
    state: latest

- name: OS X | Install AWS Shell with Homebrew
  homebrew:
    name: aws-shell
    state: latest

- name: OS X | Install AWS Vault with Homebrew
  homebrew_cask:
    name: aws-vault
    state: present

- name: OS X | Install cli53 with Homebrew
  homebrew:
    name: cli53
    state: latest
