---

- name: OS X | Install AWS CLI tools with Homebrew
  homebrew:
    name: awscli

- name: OS X | Install AWS Shell with Homebrew
  homebrew:
    name: aws-shell

- name: OS X | Install AWS Vault with Homebrew
  homebrew_cask:
    name: aws-vault

- name: OS X | Install cli53 with Homebrew
  homebrew:
    name: cli53
