---

- name: Linux | Install virtualenv
  pip:
    name: virtualenv

- name: Linux | Create directory for AWS tools
  file:
    path: "{{ aws_tools_dir }}"
    state: directory

- name: Linux | Install AWS tools in virtualenv
  pip:
    name:
    - awscli
    - aws-shell
    virtualenv: "{{ aws_tools_venv }}"
    virtualenv_python: "{{ aws_tools_python }}"

- name: Linux | Symlink AWS binaries to /usr/local/bin
  file:
    src: "{{ aws_tools_venv }}/bin/{{ item }}"
    dest: "{{ aws_bin_dir }}/{{ item }}"
    state: link
  with_items:
    - aws
    - aws-shell

- include: aws_vault.yml
- include: cli53.yml
