---

- name: Linux | Install virtualenv
  pip:
    name: virtualenv
    state: present

- name: Linux | Create directory for AWS tools
  file:
    path: "{{ aws_tools_dir }}"
    state: directory

- name: Linux | Install AWS tools in virtualenv
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ aws_tools_venv }}"
    virtualenv_python: "{{ aws_tools_python }}"
  with_items:
    - awscli
    - aws-shell

- name: Linux | Symlink AWS binaries to /usr/local/bin
  file:
    src: "{{ aws_tools_venv }}/bin/{{ item }}"
    dest: "{{ aws_bin_dir }}/{{ item }}"
    state: link
  with_items:
    - aws
    - aws-shell

- name: Linux | Create directory for AWS Vault
  file:
    path: "{{ aws_tools_dir }}/aws-vault-{{ aws_vault_version }}"
    state: directory

- name: Linux | Download aws-vault binary from GitHub
  get_url:
    url: https://github.com/99designs/aws-vault/releases/download/v{{ aws_vault_version }}/{{ aws_vault_binary }}
    dest: "{{ aws_tools_dir }}/aws-vault-{{ aws_vault_version }}/aws-vault"
    checksum: "{{ aws_vault_checksum }}"
    mode: 0755

- name: Linux | Symlink aws-vault to /usr/local/bin
  file:
    src: "{{ aws_tools_dir }}/aws-vault-{{ aws_vault_version }}/aws-vault"
    dest: "{{ aws_bin_dir }}/aws-vault"
    state: link

- name: Linux | Get aws-vault version
  command: aws-vault --version
  register: aws_vault_installed_version
  changed_when: False

- name: Linux | Check that aws-vault is not out of date
  assert:
    that: "'v{{ aws_vault_version }}' == '{{ aws_vault_installed_version.stdout }}'"
