---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ aws_tools_dir }}"
    - "{{ aws_tools_bin_dir }}"

- name: Install awscli
  include_tasks: install_awscli.yml

- name: Install aws-shell
  include_tasks: install_aws_shell.yml

- name: Install aws-vault
  include_tasks: install_aws_vault.yml
  when: aws_tools_install_aws_vault | default(true)

- name: Install cli53
  include_tasks: install_cli53.yml

- name: Configure bash
  include_tasks: shell_bash.yml

- name: Configure zsh
  include_tasks: shell_zsh.yml

- name: Remove old installation
  include_tasks: remove_old_install.yml
  when: aws_tools_remove_old_install | bool
