---
# tasks file for markosamuli.aws-tools

- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_system }}.yml"
      - "default.yml"
      paths: vars

- include: Linux.yml
  when: "{{ ansible_system == 'Linux' }}"

- include: Darwin.yml
  when: "{{ ansible_os_family == 'Darwin' }}"

- name: Install AWS MFA client
  gem: name=aws-mfa state=latest