---
# tasks file for markosamuli.aws-tools

- include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"
  - "{{ ansible_system }}.yml"
  - "default.yml"

- include: Linux.yml
  when: "{{ ansible_system == 'Linux' }}"

- include: Darwin.yml
  when: "{{ ansible_os_family == 'Darwin' }}"
