---
# tasks file for markosamuli.aws-tools

- name: Load target system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "os/{{ ansible_os_family }}.yml"
    - "os/{{ ansible_system }}_{{ ansible_architecture }}.yml"

- name: Check existing asdf installs
  include_tasks: check_asdf_installs.yml
  when: aws_tools_check_asdf_installs

- name: Install on Linux
  include_tasks: Linux.yml
  when: "ansible_system == 'Linux'"

- name: Install on macOS
  include_tasks: Darwin.yml
  when: "ansible_os_family == 'Darwin'"
