---

- name: Set path to .zshrc
  set_fact:
    aws_tools_zshrc_path: "{{ aws_tools_home }}/.zshrc"
  when: aws_tools_zshrc_path is undefined

- name: Check whether .zshrc exists
  stat:
    path: "{{ aws_tools_zshrc_path }}"
  register: aws_tools_zshrc_st

- name: Resolve .zshrc symlink
  set_fact:
    aws_tools_zshrc_path: "{{ aws_tools_zshrc_st.stat.lnk_source }}"
  when: aws_tools_zshrc_st.stat.exists and aws_tools_zshrc_st.stat.islnk

- name: Add ~/.aws-tools/bin to PATH in .zshrc
  lineinfile:
    path: "{{ aws_tools_zshrc_path }}"
    state: present
    regexp: 'export PATH=(["])?(\$HOME|~)/.aws-tools/bin:(.*)?(["])?$'
    line: '[ -d "$HOME/.aws-tools/bin" ] && export PATH="$HOME/.aws-tools/bin:$PATH"'
  when: aws_tools_zshrc_st.stat.exists
