#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT=$(dirname $DIR)

###
# Print error into STDERR
###
error() {
    echo "$@" 1>&2
}

set -e

# Variables to pass to ansible-playbook
ansible_vars=(
    '"aws_tools_remove_old_install":true'
    '"aws_tools_remove_local_install":true'
    '"aws_tools_check_asdf_installs":true'
    '"aws_tools_init_shell":true'
)
extra_vars=$(printf ",%s" "${ansible_vars[@]}")
extra_vars="{${extra_vars:1}}"

# Paths in which Ansible will search for Roles
export ANSIBLE_ROLES_PATH=$(dirname $PROJECT_ROOT)

cd $PROJECT_ROOT

echo ""
echo "*** Check syntax"

ansible-playbook tests/test.yml -i tests/inventory --syntax-check

echo ""
echo "*** Run Ansible playbook"

ansible-playbook tests/test.yml -i tests/inventory --connection=local \
    -e "${extra_vars}"

echo ""
echo "*** Idempotence test"

ansible-playbook tests/test.yml -i tests/inventory --connection=local \
    -e "${extra_vars}" \
    | grep -q 'changed=0.*failed=0' \
    && (echo 'Idempotence test: pass' && exit 0) \
    || (echo 'Idempotence test: fail' && exit 1)

echo ""
echo "*** Verify binaries"

if [ -d "$HOME/.aws-tools/bin" ]; then
    export PATH=$HOME/.aws-tools/bin:$PATH
else
    error "$HOME/.aws-tools/bin doesn't exist"
    exit 1
fi

command -v aws > /dev/null || \
    { error "aws not found"; exit 1; }
echo -n "AWS CLI version: "
aws --version

command -v aws-shell > /dev/null || \
    { error "aws-shell not found"; exit 1; }
echo "aws-shell installed"

command -v aws-vault > /dev/null || \
    { error "aws-vault not found"; exit 1; }
echo -n "aws-vault version: "
aws-vault --version

command -v cli53 > /dev/null || \
    { error "cli53 not found"; exit 1; }
echo -n "cli53 version: "
cli53 --version

command -v aws-tools-update > /dev/null || \
    { error "aws-tools-update script not found"; exit 1; }
echo "aws-tools-update script installed"
